Repository target/grease, pull requests merged in 2018-06, with the labels that each got.

#75 Update PyMongo Syntax
  setup.py
  tgt_grease/enterprise/Model/DeDuplication.py
Labels: Refactoring, bug

#79 Added generic Exception catch in Importer
  setup.py
  tgt_grease/core/Importer.py
  tgt_grease/core/tests/test_importer.py
  tgt_grease/enterprise/Sources/tests/test_sql_parser.py
Labels: bug, enhancement

#81 Hotfix/ClassNameisNone
  setup.py
  tgt_grease/core/Importer.py
  tgt_grease/router/Commands/Daemon.py
Labels: bug

#82 Fixed psycopg2 binary dependency
  setup.py
Labels: Pipeline Related
